# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: superluminal 0.8.2 ruby lib

Gem::Specification.new do |s|
  s.name = "superluminal"
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Chris Olstrom"]
  s.date = "2015-11-30"
  s.description = "Fills in some gaps in Ansible's functionality. Handles creation of IAM Roles, S3 Buckets, and VPC Peering."
  s.email = "chris@olstrom.com"
  s.executables = ["superluminal"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    ".gitignore",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "bin/superluminal",
    "example/superluminal.yaml",
    "example/templates/s3/bucket.yaml",
    "example/templates/s3/contents.yaml",
    "lib/superluminal.rb",
    "lib/superluminal/iam.rb",
    "lib/superluminal/s3.rb",
    "lib/superluminal/settings.rb",
    "lib/superluminal/vpc.rb",
    "spec/spec_helper.rb",
    "spec/superluminal_spec.rb",
    "superluminal.gemspec"
  ]
  s.homepage = "http://github.com/colstrom/superluminal"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Picking up where Ansible falls down."
  s.test_files = ["spec/spec_helper.rb", "spec/superluminal_spec.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 2.2"])
      s.add_runtime_dependency(%q<commander>, ["~> 4.3"])
      s.add_runtime_dependency(%q<multi_json>, ["~> 1.11"])
      s.add_runtime_dependency(%q<settingslogic>, ["~> 2.0"])
      s.add_runtime_dependency(%q<terminal-announce>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.4"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_development_dependency(%q<reek>, ["~> 3.7"])
      s.add_development_dependency(%q<roodi>, ["~> 5.0"])
    else
      s.add_dependency(%q<aws-sdk>, ["~> 2.2"])
      s.add_dependency(%q<commander>, ["~> 4.3"])
      s.add_dependency(%q<multi_json>, ["~> 1.11"])
      s.add_dependency(%q<settingslogic>, ["~> 2.0"])
      s.add_dependency(%q<terminal-announce>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, ["~> 3.4"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_dependency(%q<reek>, ["~> 3.7"])
      s.add_dependency(%q<roodi>, ["~> 5.0"])
    end
  else
    s.add_dependency(%q<aws-sdk>, ["~> 2.2"])
    s.add_dependency(%q<commander>, ["~> 4.3"])
    s.add_dependency(%q<multi_json>, ["~> 1.11"])
    s.add_dependency(%q<settingslogic>, ["~> 2.0"])
    s.add_dependency(%q<terminal-announce>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, ["~> 3.4"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 4.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.11"])
    s.add_dependency(%q<reek>, ["~> 3.7"])
    s.add_dependency(%q<roodi>, ["~> 5.0"])
  end
end

